import { z } from 'zod';

export const AIAnalyzePointSchema = z.object({
  x: z.number().finite(),
  y: z.number().finite(),
});

export const AIAnalyzeStrokeSchema = z.object({
  id: z.string().min(1),
  tool: z.string(),
  color: z.string().optional(),
  size: z.number().optional(),
  points: z.array(AIAnalyzePointSchema).max(500, 'Stroke exceeds maximum 500 points limit').optional().default([]),
});

export const AIObjectItemSchema = z.object({
  id: z.string(),
  type: z.string(),
  x: z.number().optional(),
  y: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  text: z.string().optional(),
  fromId: z.string().optional(),
  toId: z.string().optional(),
});

// Legacy request schema for /api/ai/analyze-diagram
export const AIAnalyzeRequestSchema = z.object({
  roomCode: z.string().min(1).max(50),
  image: z.string().max(7 * 1024 * 1024, 'Canvas snapshot image exceeds 7MB size limit').optional(),
  strokes: z.array(AIAnalyzeStrokeSchema).max(100, 'Whiteboard exceeds maximum 100 strokes limit').optional().default([]),
});

// Legacy diagram response schema
export const AIDiagramAnalysisResponseSchema = z.object({
  diagramType: z.string(),
  confidence: z.coerce.number().min(0).max(1).default(0.8),
  components: z.array(
    z.object({
      name: z.string(),
      type: z.string(),
      description: z.string(),
    })
  ).catch([]),
  relationships: z.array(
    z.object({
      from: z.string(),
      to: z.string(),
      relationship: z.string(),
    })
  ).catch([]),
  dataFlow: z.array(z.string()).catch([]),
  summary: z.string().default(''),
  potentialIssues: z.array(
    z.object({
      severity: z.enum(['low', 'medium', 'high']),
      title: z.string(),
      description: z.string(),
    })
  ).catch([]),
  suggestions: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
    })
  ).catch([]),
});

// UPGRADED AI WHITEBOARD ASSISTANT SCHEMAS

export const AIGeneratedObjectSchema = z.object({
  id: z.string(),
  type: z.enum([
    'brush',
    'eraser',
    'line',
    'arrow',
    'rectangle',
    'ellipse',
    'triangle',
    'diamond',
    'polygon',
    'text',
    'sticky',
    'connector',
  ]),
  x: z.number().optional(),
  y: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  strokeColor: z.string().optional(),
  color: z.string().optional(),
  fillColor: z.string().optional(),
  strokeWidth: z.number().optional(),
  size: z.number().optional(),
  fontSize: z.number().optional(),
  text: z.string().max(500, 'Text length exceeds 500 characters limit').optional(),
  fromId: z.string().optional(),
  toId: z.string().optional(),
  points: z.array(z.object({ x: z.number(), y: z.number() })).max(50, 'Polygon points exceed 50 points limit').optional(),
});

export const AIGenerateWhiteboardResponseSchema = z.object({
  title: z.string().default('AI Generated Whiteboard'),
  description: z.string().default('Structured whiteboard objects generated by AI.'),
  objects: z.array(AIGeneratedObjectSchema).max(100, 'Whiteboard exceeds maximum 100 objects limit'),
});

export const WhiteboardAIActionSchema = z.enum([
  'analyze',
  'summarize',
  'explain',
  'solve',
  'check',
  'generate_questions',
  'study_notes',
  'find_mistakes',
  'improve',
  'custom_question',
  'generate_whiteboard',
]);

export const WhiteboardAIContextTypeSchema = z.enum([
  'education',
  'mathematics',
  'science',
  'software',
  'business',
  'planning',
  'general',
  'unknown',
]);

export const WhiteboardAIRequestSchema = z.object({
  roomCode: z.string().min(1).max(50),
  action: WhiteboardAIActionSchema.default('analyze'),
  question: z.string().max(1000, 'Question exceeds maximum 1000 characters limit').optional().nullable(),
  image: z.string().max(7 * 1024 * 1024, 'Canvas snapshot image exceeds 7MB size limit').optional(),
  strokes: z.array(AIAnalyzeStrokeSchema).max(100, 'Whiteboard exceeds maximum 100 strokes limit').optional().default([]),
  objects: z.array(AIObjectItemSchema).max(100, 'Whiteboard exceeds maximum 100 objects limit').optional().default([]),
});

export const WhiteboardAIResponseSchema = z.object({
  context: z.object({
    type: WhiteboardAIContextTypeSchema.catch('general'),
    label: z.string().default('Whiteboard Content'),
    confidence: z.coerce.number().min(0).max(1).default(0.8),
  }),
  observations: z.array(z.string()).catch([]),
  inferences: z.array(z.string()).catch([]),
  uncertainties: z.array(z.string()).catch([]),
  summary: z.string().default('Summary of whiteboard content.'),
  keyPoints: z.array(z.string()).catch([]),
  analysis: z
    .object({
      explanation: z.string().optional(),
      mistakes: z.array(z.string()).catch([]).optional(),
      suggestions: z.array(z.string()).catch([]).optional(),
      stepByStep: z.array(z.string()).catch([]).optional(),
    })
    .default({}),
  questions: z.array(z.string()).catch([]),
  customAnswer: z.string().optional(),
  generatedContent: AIGenerateWhiteboardResponseSchema.optional(),
});

export type AIAnalyzeRequest = z.infer<typeof AIAnalyzeRequestSchema>;
export type AIDiagramAnalysisResponse = z.infer<typeof AIDiagramAnalysisResponseSchema>;
export type WhiteboardAIAction = z.infer<typeof WhiteboardAIActionSchema>;
export type WhiteboardAIContextType = z.infer<typeof WhiteboardAIContextTypeSchema>;
export type WhiteboardAIRequest = z.infer<typeof WhiteboardAIRequestSchema>;
export type WhiteboardAIResponse = z.infer<typeof WhiteboardAIResponseSchema>;
export type AIGeneratedObject = z.infer<typeof AIGeneratedObjectSchema>;
export type AIGenerateWhiteboardResponse = z.infer<typeof AIGenerateWhiteboardResponseSchema>;
