import {
  AIAnalyzeRequest,
  AIDiagramAnalysisResponse,
  AIDiagramAnalysisResponseSchema,
  AIGenerateWhiteboardResponse,
  AIGenerateWhiteboardResponseSchema,
  WhiteboardAIRequest,
  WhiteboardAIResponse,
  WhiteboardAIResponseSchema,
} from '../validators/aiSchemas.js';
import {
  SmartInkRequest,
  SmartInkResponse,
  SmartInkResponseSchema,
} from '../validators/aiSmartInkSchemas.js';
import {
  LectureRequest,
  StructuredLectureNotesSchema,
  LectureQuizResponseSchema,
  LectureFlashcardsResponseSchema,
  LectureQAResponseSchema,
} from '../validators/lectureSchemas.js';

export class AIService {
  private get apiKey(): string {
    return process.env.AI_API_KEY || '';
  }

  private get modelName(): string {
    return process.env.AI_MODEL || 'gemini-flash-latest';
  }

  public isConfigured(): boolean {
    return Boolean(this.apiKey && this.apiKey.trim().length > 0);
  }

  /**
   * Deterministic layout sanitizer and bounds validator layer
   */
  public sanitizeAndAdjustLayout(data: AIGenerateWhiteboardResponse): AIGenerateWhiteboardResponse {
    const rawObjects = data.objects || [];
    const MAX_AI_OBJECTS = 100;
    const MAX_TEXT_LENGTH = 500;
    const MAX_POLYGON_POINTS = 50;

    const sanitizedObjects: any[] = [];
    const seenIds = new Set<string>();

    for (let i = 0; i < Math.min(rawObjects.length, MAX_AI_OBJECTS); i++) {
      const obj = rawObjects[i];
      let id = obj.id || `obj-${i + 1}`;
      if (seenIds.has(id)) {
        id = `${id}-${i + 1}`;
      }
      seenIds.add(id);

      // Clamp text length
      let text = obj.text;
      if (text && text.length > MAX_TEXT_LENGTH) {
        text = text.substring(0, MAX_TEXT_LENGTH);
      }

      // Clamp polygon points
      let points = obj.points;
      if (points && points.length > MAX_POLYGON_POINTS) {
        points = points.slice(0, MAX_POLYGON_POINTS);
      }

      // Coordinate normalization safety
      let x = typeof obj.x === 'number' ? obj.x : 0.1 + (i % 5) * 0.18;
      let y = typeof obj.y === 'number' ? obj.y : 0.15 + Math.floor(i / 5) * 0.18;
      let width = typeof obj.width === 'number' ? obj.width : 0.15;
      let height = typeof obj.height === 'number' ? obj.height : 0.08;

      // Keep within bounds [0.02, 0.95]
      x = Math.max(0.02, Math.min(0.95, x));
      y = Math.max(0.02, Math.min(0.95, y));
      width = Math.max(0.02, Math.min(0.8, width));
      height = Math.max(0.02, Math.min(0.8, height));

      // Color mapping
      const color = obj.color || obj.strokeColor || '#000000';
      const fillColor = obj.fillColor || (['sticky'].includes(obj.type) ? '#FEF08A' : '#FFFFFF');
      const size = obj.size || obj.strokeWidth || 2;
      const fontSize = obj.fontSize || 14;

      sanitizedObjects.push({
        ...obj,
        id,
        x,
        y,
        width,
        height,
        color,
        fillColor,
        size,
        fontSize,
        text,
        points,
      });
    }

    // Verify connector reference validity
    const validIds = new Set(sanitizedObjects.map((o) => o.id));
    for (const obj of sanitizedObjects) {
      if (obj.fromId && !validIds.has(obj.fromId)) {
        obj.fromId = undefined;
      }
      if (obj.toId && !validIds.has(obj.toId)) {
        obj.toId = undefined;
      }
    }

    return {
      title: data.title || 'AI Generated Whiteboard',
      description: data.description || 'Structured whiteboard objects generated by AI.',
      objects: sanitizedObjects,
    };
  }

  /**
   * General-Purpose AI Whiteboard Assistant generation (Natural Language to Drawable Objects)
   */
  public async generateWhiteboard(payload: WhiteboardAIRequest): Promise<WhiteboardAIResponse> {
    if (!this.isConfigured()) {
      throw new Error('AI Provider API Key (AI_API_KEY) is missing or not configured on the server.');
    }

    const userQuestion = payload.question || 'Create a software architecture diagram';

    const systemPrompt = `You are an expert AI system generating structured drawable objects for a collaborative whiteboard.
Return ONLY valid JSON matching this schema:
{
  "title": "Short title describing the whiteboard design",
  "description": "Short description of what was drawn",
  "objects": [
    {
      "id": "obj-1",
      "type": "rectangle" | "ellipse" | "triangle" | "diamond" | "polygon" | "text" | "sticky" | "arrow" | "line" | "connector",
      "x": 0.10,
      "y": 0.20,
      "width": 0.15,
      "height": 0.10,
      "text": "Label text",
      "strokeColor": "#000000",
      "fillColor": "#FFFFFF",
      "strokeWidth": 2
    },
    {
      "id": "obj-2",
      "type": "arrow",
      "fromId": "obj-1",
      "toId": "obj-3",
      "text": "connector label optional"
    }
  ]
}

CRITICAL RULES FOR GENERATION:
1. Return ONLY valid JSON. Do NOT wrap in \`\`\`json.
2. Use normalized coordinates (0.0 to 1.0) for x, y, width, height.
   - Example: x: 0.10 is 10% from left, y: 0.30 is 30% from top.
3. PREFER CLEAR & READABLE LAYOUTS:
   - Avoid overlapping shapes.
   - For Flowcharts: Top to bottom or left to right sequence with diamonds for decision steps.
   - For Architecture: Horizontal or multi-layer layout (User -> API -> Microservice -> Database).
   - For Kanban: 3 vertical columns (Todo, In Progress, Done) with sticky notes inside columns.
   - For Mind Maps: Central ellipse node with branching arrows connecting sub-topic nodes.
   - For Science/Water Cycle/Photosynthesis: Cycle flow with directional arrows and explanatory text labels.
   - For Math: Clear horizontal or vertical equations with text labels and sticky note explanations.
4. Use arrows/connectors to represent relationships. Reference valid fromId and toId shape IDs.
5. Maximum 100 objects total. Keep labels concise.`;

    const userPromptText = `User Request: "${userQuestion}"
${(payload.objects || []).length > 0 ? `Existing Board Objects Count: ${payload.objects.length}` : ''}`;

    const parts: any[] = [{ text: `${systemPrompt}\n\n${userPromptText}` }];

    if (payload.image) {
      const base64Data = payload.image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          mimeType: 'image/png',
          data: base64Data,
        },
      });
    }

    const candidateModels = Array.from(
      new Set([this.modelName, 'gemini-2.5-flash', 'gemini-flash-latest', 'gemini-3.5-flash'])
    );
    let lastError: string = '';
    let responseData: any = null;

    for (const model of candidateModels) {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts,
            },
          ],
          generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 4096,
            responseMimeType: 'application/json',
          },
        }),
      });

      if (response.ok) {
        responseData = await response.json();
        break;
      }

      const errorText = await response.text();
      console.warn(`[AIService] Model ${model} returned status ${response.status}: ${errorText.substring(0, 150)}`);
      lastError = `AI Provider HTTP Error (${response.status}): ${errorText.substring(0, 100)}`;
      if (response.status !== 404 && response.status !== 503 && response.status !== 429) {
        break;
      }
    }

    if (!responseData) {
      throw new Error(lastError || 'AI Provider failed to generate whiteboard objects.');
    }

    const candidateText = responseData?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText || typeof candidateText !== 'string') {
      throw new Error('AI Provider returned an empty candidate response.');
    }

    const cleanedText = candidateText
      .trim()
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```$/i, '')
      .trim();

    let rawParsed: unknown;
    try {
      rawParsed = JSON.parse(cleanedText);
    } catch (e: any) {
      console.error('[AIService] Failed to parse generated JSON:', cleanedText);
      throw new Error(`AI generation output was not valid JSON: ${e.message}`);
    }

    let parsedResponse = AIGenerateWhiteboardResponseSchema.parse(rawParsed);
    const sanitized = this.sanitizeAndAdjustLayout(parsedResponse);

    return {
      context: {
        type: 'general',
        label: sanitized.title,
        confidence: 0.95,
      },
      observations: [`Generated ${sanitized.objects.length} structured whiteboard objects.`],
      inferences: [sanitized.description],
      uncertainties: [],
      summary: `${sanitized.title}: ${sanitized.description}`,
      keyPoints: sanitized.objects.map((o) => `${o.type}: ${o.text || o.id}`),
      analysis: {
        explanation: `AI generated layout containing ${sanitized.objects.length} items.`,
      },
      questions: [],
      generatedContent: sanitized,
    };
  }

  /**
   * General-Purpose AI Whiteboard Assistant analysis
   */
  public async analyzeWhiteboard(payload: WhiteboardAIRequest): Promise<WhiteboardAIResponse> {
    if (!this.isConfigured()) {
      throw new Error('AI Provider API Key (AI_API_KEY) is missing or not configured on the server.');
    }

    const action = payload.action || 'analyze';

    // Route generate_whiteboard action directly to generateWhiteboard
    if (action === 'generate_whiteboard') {
      return this.generateWhiteboard(payload);
    }

    const userQuestion = payload.question || '';

    const systemPrompt = `You are an expert multimodal AI assistant specialized in analyzing collaborative whiteboard content.
The whiteboard may contain classroom lecture notes, mathematical equations, physics/biology/chemistry diagrams, flowcharts, software architecture, business workflows, mind maps, project plans, or general sketches.

DO NOT force every whiteboard into a software architecture diagram. Determine the TRUE content type dynamically:
- 'education': Lecture notes, classroom explanations, lesson concepts, key terms.
- 'mathematics': Equations, algebraic formulas, geometric figures, calculus, step-by-step math problems.
- 'science': Physics diagrams, biology illustrations, chemical structures, lab setups.
- 'software': System architecture, API flows, database schemas, microservices, code snippets.
- 'business': Flowcharts, process maps, org charts, strategy diagrams, swimlanes.
- 'planning': Kanban boards, project timelines, task lists, mind maps.
- 'general': Unstructured sketches, drawings, or miscellaneous visual elements.
- 'unknown': Sparsely drawn strokes or unrecognizable markings.

STRICT GROUNDING & SEPARATION RULES:
1. "observations": List ONLY things actually visible/detectable in the whiteboard strokes or image (e.g. text labels, drawn shapes, color coding, equations, connecting arrows).
2. "inferences": List reasonable interpretations derived from observations (e.g. "This equation appears to represent solving a linear variable", "The arrow suggests a data request from Client to API Gateway").
3. "uncertainties": List ambiguous or low-confidence details (e.g. "The handwritten symbol next to the equation is unclear", "Unlabeled box between database and backend").
4. Never hallucinate or invent information unsupported by the whiteboard.

REQUEST ACTION & INTENT:
The requested action is: "${action}".
${userQuestion ? `The user specifically asked: "${userQuestion}"` : ''}

Tailor your output to address the requested action ("${action}"):
- If action is "solve": Provide step-by-step resolution in "analysis.stepByStep". Show clear mathematical or logical reasoning.
- If action is "find_mistakes": Identify errors, bugs, or logical flaws in "analysis.mistakes".
- If action is "explain": Provide a clear explanation tailored to the detected context in "analysis.explanation".
- If action is "study_notes": Generate concise summary, key points, and flashcard-style study notes.
- If action is "generate_questions": Create 3-5 relevant quiz or practice questions in "questions".
- If action is "improve": Provide optimization or enhancement recommendations in "analysis.suggestions".
- If action is "custom_question": Answer the user's specific question in "customAnswer" grounded strictly in the whiteboard content.

OUTPUT SCHEMA REQUIREMENTS:
Return strictly valid raw JSON matching this structure:
{
  "context": {
    "type": "education" | "mathematics" | "science" | "software" | "business" | "planning" | "general" | "unknown",
    "label": "Human readable label (e.g. Mathematics Equation, Biology Diagram, 3-Tier Architecture)",
    "confidence": number between 0.0 and 1.0
  },
  "observations": ["observed fact 1", "observed fact 2"],
  "inferences": ["inference 1", "inference 2"],
  "uncertainties": ["uncertainty 1"],
  "summary": "Overall summary of what is on the board",
  "keyPoints": ["key point 1", "key point 2"],
  "analysis": {
    "explanation": "Detailed explanation if applicable",
    "mistakes": ["mistake 1 if found"],
    "suggestions": ["improvement suggestion 1"],
    "stepByStep": ["step 1", "step 2"]
  },
  "questions": ["question 1", "question 2"],
  "customAnswer": "Detailed response to custom question if requested"
}

Return ONLY raw JSON. Do NOT include markdown code block wrappers (do NOT use \`\`\`json), explanations, or preambles.`;

    // Hybrid context summary from stroke metadata and structured objects
    const strokesSummary = (payload.strokes || []).map((s, idx) => ({
      strokeIndex: idx + 1,
      tool: s.tool,
      color: s.color,
      strokeSize: s.size,
      pointCount: (s.points || []).length,
      startPoint: s.points?.[0],
      endPoint: s.points?.[s.points.length - 1],
    }));

    const objectsSummary = (payload.objects || []).map((obj) => ({
      id: obj.id,
      type: obj.type,
      x: obj.x,
      y: obj.y,
      width: obj.width,
      height: obj.height,
      color: obj.color,
      fillColor: obj.fillColor,
      text: obj.text,
      fromId: obj.fromId,
      toId: obj.toId,
    }));

    const userPromptText = `Whiteboard Room Code: ${payload.roomCode}
Requested Action: ${action}
${userQuestion ? `User Question: ${userQuestion}` : ''}
Total Active Freehand Strokes: ${(payload.strokes || []).length}
Stroke Summary Data: ${JSON.stringify(strokesSummary, null, 2)}
Structured Whiteboard Objects (${(payload.objects || []).length}): ${JSON.stringify(objectsSummary, null, 2)}`;

    // Build Gemini API multi-modal request
    const parts: any[] = [{ text: `${systemPrompt}\n\n${userPromptText}` }];

    if (payload.image) {
      // Extract base64 image data
      const base64Data = payload.image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          mimeType: 'image/png',
          data: base64Data,
        },
      });
    }

    const candidateModels = Array.from(
      new Set([this.modelName, 'gemini-2.5-flash', 'gemini-flash-latest', 'gemini-3.5-flash'])
    );
    let lastError: string = '';
    let responseData: any = null;

    for (const model of candidateModels) {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts,
            },
          ],
          generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 2048,
            responseMimeType: 'application/json',
          },
        }),
      });

      if (response.ok) {
        responseData = await response.json();
        break;
      }

      const errorText = await response.text();
      console.warn(`[AIService] Model ${model} returned status ${response.status}: ${errorText.substring(0, 150)}`);
      lastError = `AI Provider HTTP Error (${response.status}): ${errorText.substring(0, 100)}`;
      if (response.status !== 404 && response.status !== 503 && response.status !== 429) {
        break;
      }
    }

    if (!responseData) {
      throw new Error(lastError || 'AI Provider failed to return a response.');
    }

    const candidateText = responseData?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!candidateText || typeof candidateText !== 'string') {
      throw new Error('AI Provider returned an empty or invalid candidate response.');
    }

    // Clean JSON text (strip Markdown formatting if present)
    const cleanedText = candidateText
      .trim()
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```$/i, '')
      .trim();

    let rawParsed: unknown;
    try {
      rawParsed = JSON.parse(cleanedText);
    } catch (e: any) {
      console.error('[AIService] Failed to parse JSON output:', cleanedText);
      throw new Error(`AI response was not valid JSON: ${e.message}`);
    }

    // Strict Zod Validation of AI Response with resilient fallbacks
    const parsedRes = WhiteboardAIResponseSchema.safeParse(rawParsed);
    if (parsedRes.success) {
      return parsedRes.data;
    }

    console.warn('[AIService] Zod schema mismatch, applying resilient defaults:', parsedRes.error.format());
    const obj: any = typeof rawParsed === 'object' && rawParsed !== null ? rawParsed : {};
    return {
      context: {
        type: (obj.context?.type as any) || 'general',
        label: obj.context?.label || 'Whiteboard Content',
        confidence: typeof obj.context?.confidence === 'number' ? obj.context.confidence : 0.8,
      },
      observations: Array.isArray(obj.observations) ? obj.observations : [],
      inferences: Array.isArray(obj.inferences) ? obj.inferences : [],
      uncertainties: Array.isArray(obj.uncertainties) ? obj.uncertainties : [],
      summary: typeof obj.summary === 'string' ? obj.summary : 'Whiteboard analysis summary.',
      keyPoints: Array.isArray(obj.keyPoints) ? obj.keyPoints : [],
      analysis: typeof obj.analysis === 'object' && obj.analysis !== null ? obj.analysis : {},
      questions: Array.isArray(obj.questions) ? obj.questions : [],
      customAnswer: typeof obj.customAnswer === 'string' ? obj.customAnswer : undefined,
    };
  }

  /**
   * Legacy method for backward compatibility with /api/ai/analyze-diagram
   */
  public async analyzeDiagram(payload: AIAnalyzeRequest): Promise<AIDiagramAnalysisResponse> {
    const generalResult = await this.analyzeWhiteboard({
      roomCode: payload.roomCode,
      action: 'analyze',
      strokes: payload.strokes,
      objects: [],
      image: payload.image,
    });

    // Map WhiteboardAIResponse back to legacy AIDiagramAnalysisResponse schema
    const legacyResponse: AIDiagramAnalysisResponse = {
      diagramType: generalResult.context.label || 'Whiteboard Diagram',
      confidence: generalResult.context.confidence || 0.8,
      components: generalResult.observations.map((obs, i) => ({
        name: `Component ${i + 1}`,
        type: generalResult.context.type,
        description: obs,
      })),
      relationships: generalResult.inferences.map((inf) => ({
        from: 'System Entity',
        to: 'Target Entity',
        relationship: inf,
      })),
      dataFlow: generalResult.keyPoints.length > 0 ? generalResult.keyPoints : [generalResult.summary],
      summary: generalResult.summary,
      potentialIssues: (generalResult.analysis.mistakes || []).map((m) => ({
        severity: 'medium' as const,
        title: 'Observation Warning',
        description: m,
      })),
      suggestions: (generalResult.analysis.suggestions || []).map((s) => ({
        title: 'Recommendation',
        description: s,
      })),
    };

    return AIDiagramAnalysisResponseSchema.parse(legacyResponse);
  }

  /**
   * Smart Ink Intelligence: Context-Aware Handwriting Recognition
   */
  public async recognizeSmartInk(payload: SmartInkRequest): Promise<SmartInkResponse> {
    if (!this.isConfigured()) {
      throw new Error('AI API Key is missing on the server. Unable to process Smart Ink recognition.');
    }

    const { strokeGroup, boardContext, image } = payload;
    const nearbyTexts = (boardContext?.nearbyText || []).filter(Boolean);
    const existingTexts = (boardContext?.existingObjects || [])
      .map((o) => o.text)
      .filter((t): t is string => Boolean(t && t.trim().length > 0));

    const combinedContext = Array.from(new Set([...nearbyTexts, ...existingTexts]));

    const systemPrompt = `You are Smart Ink Intelligence, an expert context-aware handwriting recognition engine for interactive whiteboards.
Your job is to read handwritten pen strokes and convert them into clean digital text, mathematical equations, or chemical/scientific notation.

CRITICAL RULES FOR RECOGNITION:
1. CONTEXT AWARENESS:
   - Use surrounding board text to disambiguate ambiguous letters (e.g., if board has "Apple", "Banana", favor fruit names).
   - Recognize math equations (e.g., "x² + 5x + 6 = 0" or "a^2 + b^2 = c^2"). Set category to "math" and provide latex string if applicable.
   - Recognize chemical/scientific notation (e.g., "CO2 + H2O → Glucose + O2" or "NaCl"). Set category to "science".
2. GROUNDING & CONFIDENCE:
   - Provide realistic confidence score between 0.0 and 1.0 based on visual clarity and contextual alignment.
   - Grounding observation: describe what is visibly written.
   - Grounding interpretation: explain why this candidate was selected.
   - Grounding uncertainty: note any letter ambiguities.
3. OUTPUT FORMAT:
   - Must return strict JSON conforming to:
     {
       "primary": "Best candidate text",
       "candidates": ["Alternative 1", "Alternative 2"],
       "confidence": 0.95,
       "category": "text" | "math" | "science" | "number",
       "latex": "optional latex string",
       "grounding": {
         "observation": "Visually observed letter sequence...",
         "interpretation": "Contextually matched word...",
         "uncertainty": "Letter 'p' vs 'r' ambiguity..."
       }
     }`;

    const contextDescription = combinedContext.length > 0
      ? `Surrounding Board Context Words: [${combinedContext.slice(0, 15).join(', ')}]`
      : 'No surrounding board text present.';

    const userPromptText = `Handwritten Bounding Box: x=${strokeGroup.bounds.x.toFixed(3)}, y=${strokeGroup.bounds.y.toFixed(3)}, w=${strokeGroup.bounds.width.toFixed(3)}, h=${strokeGroup.bounds.height.toFixed(3)}.
Stroke Count: ${strokeGroup.strokes.length}.
${contextDescription}

Recognize the handwritten content and return the JSON response:`;

    const parts: any[] = [{ text: `${systemPrompt}\n\n${userPromptText}` }];

    if (image) {
      const base64Data = image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          mimeType: 'image/png',
          data: base64Data,
        },
      });
    }

    const candidateModels = Array.from(
      new Set([this.modelName, 'gemini-3.6-flash', 'gemini-3.5-flash', 'gemini-flash-latest', 'gemini-2.5-flash-lite'])
    );
    let lastError = '';
    let responseData: any = null;

    for (const model of candidateModels) {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts }],
          generationConfig: {
            temperature: 0.1,
            maxOutputTokens: 1024,
            responseMimeType: 'application/json',
          },
        }),
      });

      if (response.ok) {
        responseData = await response.json();
        break;
      }

      const errText = await response.text();
      console.warn(`[AIService SmartInk] Model ${model} HTTP ${response.status}: ${errText.substring(0, 150)}`);
      lastError = `Smart Ink AI Error (${response.status}): ${errText.substring(0, 100)}`;
      if (response.status !== 404 && response.status !== 503 && response.status !== 429) {
        break;
      }
    }

    if (!responseData) {
      throw new Error(lastError || 'Smart Ink AI provider request failed.');
    }

    const rawText = responseData?.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
    let rawParsed: any = {};
    try {
      rawParsed = JSON.parse(rawText);
    } catch {
      console.warn('[AIService SmartInk] Failed to parse JSON response:', rawText);
    }

    const parsedRes = SmartInkResponseSchema.safeParse(rawParsed);
    if (parsedRes.success) {
      return parsedRes.data;
    }

    console.warn('[AIService SmartInk] Schema mismatch, applying safe defaults:', parsedRes.error.format());
    const primaryText = typeof rawParsed.primary === 'string' ? rawParsed.primary : 'Unrecognized Ink';

    return {
      primary: primaryText,
      candidates: Array.isArray(rawParsed.candidates) ? rawParsed.candidates : [],
      confidence: typeof rawParsed.confidence === 'number' ? rawParsed.confidence : 0.7,
      category: ['text', 'math', 'science', 'number'].includes(rawParsed.category) ? rawParsed.category : 'text',
      latex: typeof rawParsed.latex === 'string' ? rawParsed.latex : undefined,
      grounding: {
        observation: rawParsed.grounding?.observation || 'Visual stroke handwriting',
        interpretation: rawParsed.grounding?.interpretation || 'Matched candidate',
        uncertainty: rawParsed.grounding?.uncertainty || 'None',
      },
    };
  }

  /**
   * 🎓 LIVE LECTURE INTELLIGENCE
   * Analyzes evolving lecture event history, semantic snapshots, and canvas state using Gemini
   */
  public async analyzeLectureSession(payload: LectureRequest): Promise<any> {
    if (!this.isConfigured()) {
      throw new Error('AI Provider API Key (AI_API_KEY) is missing or not configured on the server.');
    }

    const { action, roomCode, startedAt, endedAt, events, snapshots, currentStrokes, image, userQuestion } = payload;
    const durationSeconds = Math.max(1, Math.round(((endedAt || Date.now()) - startedAt) / 1000));
    const durationMinutes = Math.round(durationSeconds / 60);

    // Format events & snapshots timeline
    const timelineSummary = events.map((e) => `[+${e.timeOffsetSeconds}s] ${e.type}: ${e.summary}${e.text ? ` ("${e.text}")` : ''}`).join('\n');
    const snapshotSummary = snapshots.map((s) => `[+${s.timeOffsetSeconds}s] Objects: ${s.objectCount} | Summary: ${s.textSummary}`).join('\n');

    // Extract text and objects from current board
    const strokeTexts = currentStrokes.map((s) => s.text).filter(Boolean).join('; ');

    const groundingInstructions = `
CRITICAL GROUNDING RULES:
1. Every claim must be grounded in OBSERVATIONS from the actual board content, event timeline, or canvas image.
2. Provide explicit grounding arrays:
   - "observations": List directly visible facts/objects from the board/timeline.
   - "inferences": List interpretations/deductions derived from the board.
   - "uncertainties": List ambiguous, unclear, or unspecified elements.
3. Do NOT hallucinate unwritten concepts as facts. Clearly mark suggestions as "Possible missing concept" or "Possible confusion".`;

    let systemPrompt = '';
    let targetSchema: any = StructuredLectureNotesSchema;

    switch (action) {
      case 'quiz': {
        targetSchema = LectureQuizResponseSchema;
        systemPrompt = `You are an expert educational AI creating a grounded assessment quiz from a live lecture whiteboard session.
Return ONLY valid JSON matching this schema:
{
  "lectureTitle": "Title of the lecture",
  "quizTitle": "Lecture Self-Assessment Quiz",
  "questions": [
    {
      "id": "q-1",
      "type": "multiple_choice" | "short_answer" | "conceptual",
      "question": "Clear question based strictly on lecture content",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctAnswer": "Option A",
      "explanation": "Explanation grounded in board content"
    }
  ],
  "grounding": { "observations": [...], "inferences": [...], "uncertainties": [...] }
}

${groundingInstructions}`;
        break;
      }

      case 'flashcards': {
        targetSchema = LectureFlashcardsResponseSchema;
        systemPrompt = `You are an expert study assistant generating flashcards from a live lecture whiteboard.
Return ONLY valid JSON matching this schema:
{
  "lectureTitle": "Title of the lecture",
  "flashcards": [
    {
      "id": "fc-1",
      "front": "Question or Key Term from board",
      "back": "Grounded explanation based on lecture content",
      "category": "Term / Equation / Process"
    }
  ],
  "grounding": { "observations": [...], "inferences": [...], "uncertainties": [...] }
}

${groundingInstructions}`;
        break;
      }

      case 'ask_question': {
        targetSchema = LectureQAResponseSchema;
        systemPrompt = `You are an expert grounded AI lecture tutor answering a student's question about a live lecture.
Return ONLY valid JSON matching this schema:
{
  "lectureTitle": "Title of the lecture",
  "question": "${userQuestion || 'Question about lecture'}",
  "answer": "Clear, helpful answer strictly grounded in what was taught/drawn on the board",
  "relevantTimeOffset": "Timestamp/offset if relevant",
  "grounding": { "observations": [...], "inferences": [...], "uncertainties": [...] }
}

${groundingInstructions}`;
        break;
      }

      case 'notes':
      case 'progression':
      case 'what_changed':
      case 'missing_concepts':
      case 'possible_confusion':
      default: {
        targetSchema = StructuredLectureNotesSchema;
        systemPrompt = `You are an expert AI Lecture Intelligence system transforming an evolving live whiteboard into structured learning material.
Return ONLY valid JSON matching this schema:
{
  "lectureTitle": "Structured title of the lecture",
  "mainTopic": "Main topic taught",
  "durationMinutes": ${durationMinutes},
  "keyConcepts": ["Concept 1", "Concept 2"],
  "definitions": [{ "term": "Term", "definition": "Meaning" }],
  "processes": [{ "title": "Process Name", "steps": ["Step 1", "Step 2"] }],
  "equations": [{ "formula": "Formula", "explanation": "Explanation" }],
  "examples": ["Example 1"],
  "relationships": ["Relationship 1"],
  "keyTakeaways": ["Takeaway 1"],
  "reviewQuestions": ["Question 1", "Question 2"],
  "lectureProgression": [
    { "step": 1, "timeLabel": "+0m", "description": "Step description of how lecture evolved" }
  ],
  "whatChanged": ["Semantic change 1", "Semantic change 2"],
  "possibleMissingConcepts": ["Possible missing concept: Chlorophyll"],
  "possibleConfusions": ["Possible ambiguity: Relationship between CO2 and O2 flow"],
  "grounding": {
    "observations": ["CO2 + H2O and sunlight are written"],
    "inferences": ["These represent inputs to photosynthesis"],
    "uncertainties": ["Exact role of arrow is unstated"]
  }
}

${groundingInstructions}`;
        break;
      }
    }

    const userPromptText = `LECTURE METADATA:
Room: #${roomCode}
Duration: ~${durationMinutes} minutes (${durationSeconds} seconds)
${userQuestion ? `Student Question: "${userQuestion}"` : ''}

EVENT TIMELINE (${events.length} events):
${timelineSummary || 'No event timeline recorded.'}

SEMANTIC SNAPSHOTS (${snapshots.length} snapshots):
${snapshotSummary || 'No snapshots recorded.'}

CURRENT BOARD CONTENT (${currentStrokes.length} objects):
Text content on board: ${strokeTexts || 'None'}

Please analyze the evolution of this lecture whiteboard and generate the requested response.`;

    const parts: any[] = [{ text: `${systemPrompt}\n\n${userPromptText}` }];

    if (image) {
      const base64Data = image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.push({
        inlineData: {
          mimeType: 'image/png',
          data: base64Data,
        },
      });
    }

    const candidateModels = Array.from(
      new Set([this.modelName, 'gemini-2.5-flash', 'gemini-flash-latest', 'gemini-3.5-flash'])
    );

    let lastError: string = '';
    let responseData: any = null;
    let usedModelName = '';

    for (const model of candidateModels) {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts }],
          generationConfig: {
            temperature: 0.1,
            maxOutputTokens: 2048,
            responseMimeType: 'application/json',
          },
        }),
      });

      if (response.ok) {
        responseData = await response.json();
        usedModelName = model;
        break;
      }

      const errText = await response.text();
      console.warn(`[AIService Lecture] Model ${model} HTTP ${response.status}: ${errText.substring(0, 150)}`);
      lastError = `Lecture AI Error (${response.status}): ${errText.substring(0, 100)}`;
      if (response.status !== 404 && response.status !== 503 && response.status !== 429) {
        break;
      }
    }

    if (!responseData) {
      console.log('[Lecture AI] Provider: Fallback | Fallback Used: true');
      const observedTexts = currentStrokes.map((s) => s.text).filter(Boolean);
      const firstTopic = observedTexts[0] || 'Interactive Whiteboard Lecture';
      const eventSummaries = events.map((e) => e.summary);

      const providerMetadata = { provider: 'fallback' as const, fallbackUsed: true };

      if (action === 'quiz') {
        return {
          lectureTitle: `Quiz: ${firstTopic}`,
          quizTitle: `Quiz: ${firstTopic}`,
          questions: [
            {
              id: 'q-1',
              type: 'multiple_choice',
              question: `Based on the lecture notes on "${firstTopic}", which of the following is a primary component?`,
              options: observedTexts.length > 0 ? observedTexts.slice(0, 4) : ['Option A', 'Option B', 'Option C', 'Option D'],
              correctAnswer: observedTexts[0] || 'Option A',
              explanation: 'Grounded directly in board text content created during lecture.',
            },
            {
              id: 'q-2',
              type: 'conceptual',
              question: `Explain how the elements recorded in this lecture relate to the main topic: ${firstTopic}.`,
              correctAnswer: 'Answers should reference the key formulas and diagrams added to the whiteboard.',
              explanation: 'Grounded in structural board evolution.',
            },
          ],
          grounding: {
            observations: observedTexts.slice(0, 5),
            inferences: ['Generated structured quiz from verified lecture events'],
            uncertainties: ['Additional verbal context may clarify option choices'],
          },
          providerMetadata,
        };
      }

      if (action === 'flashcards') {
        return {
          lectureTitle: `Flashcards: ${firstTopic}`,
          flashcards: observedTexts.length > 0
            ? observedTexts.map((txt, idx) => ({
                id: `card-${idx + 1}`,
                front: `Key Term / Concept ${idx + 1}`,
                back: txt,
                category: 'Lecture Concept',
              }))
            : [
                {
                  id: 'card-1',
                  front: 'Main Lecture Topic',
                  back: firstTopic,
                  category: 'Whiteboard Note',
                },
              ],
          grounding: {
            observations: observedTexts.slice(0, 5),
            inferences: ['Created review flashcards directly from lecture content'],
            uncertainties: [],
          },
          providerMetadata,
        };
      }

      if (action === 'ask_question') {
        return {
          lectureTitle: firstTopic,
          question: userQuestion || 'Lecture clarification',
          answer: `Based on the recorded whiteboard content for "${firstTopic}": ${observedTexts.join('; ') || 'The lecture focused on visual board drawings and notes.'}`,
          grounding: {
            observations: observedTexts.slice(0, 5),
            inferences: ['Answer grounded directly in verified board strokes'],
            uncertainties: userQuestion ? [] : ['No specific question was specified'],
          },
          providerMetadata,
        };
      }

      // Default: 'notes'
      return {
        lectureTitle: `Structured Lecture Notes: ${firstTopic.slice(0, 40)}`,
        mainTopic: firstTopic,
        durationMinutes,
        keyConcepts: observedTexts.length > 0 ? observedTexts : ['Live Whiteboard Concepts'],
        definitions: observedTexts.map((t) => ({ term: t.split(':')[0] || t, definition: t.split(':')[1] || 'Lecture term' })),
        processes: [],
        equations: [],
        examples: [],
        relationships: [],
        keyTakeaways: ['Review active board elements and snapshots recorded during session'],
        reviewQuestions: [`What are the core principles behind ${firstTopic}?`],
        lectureProgression: snapshots.map((s, idx) => ({
          step: idx + 1,
          timeLabel: `+${Math.floor(s.timeOffsetSeconds / 60)}m`,
          description: s.textSummary || `Board Snapshot ${idx + 1}`,
        })),
        whatChanged: eventSummaries.length > 0 ? eventSummaries : ['Board content created during lecture'],
        possibleMissingConcepts: [
          {
            suggestion: 'Consider reviewing formal proof or step-by-step reaction steps',
            reason: 'Board content focuses on core equations but omits intermediate steps.',
            evidence: events.map((e) => e.id).slice(0, 3),
          },
        ],
        possibleConfusions: [
          {
            suggestion: 'Verify connector lines and arrow flow directions',
            reason: 'Multiple visual objects created without explicit directional connectors.',
            evidence: events.map((e) => e.id).slice(0, 3),
          },
        ],
        grounding: {
          observations: observedTexts.slice(0, 5),
          inferences: ['Synthesized from live lecture timeline and active board state'],
          uncertainties: ['Spoken audio lecture stream not attached'],
        },
        providerMetadata,
      };
    }

    console.log(`[Lecture AI] Provider: Gemini | Model: ${usedModelName} | Fallback Used: false`);

    const rawText = responseData?.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
    let rawParsed: any = {};
    try {
      rawParsed = JSON.parse(rawText);
    } catch {
      console.warn('[AIService Lecture] Failed to parse JSON response:', rawText);
    }

    // Normalize property key variations from Gemini AI response
    if (rawParsed && typeof rawParsed === 'object') {
      const firstBoardText = currentStrokes.map((s) => s.text).filter(Boolean)[0] || 'Interactive Whiteboard Lecture';
      rawParsed.mainTopic = rawParsed.mainTopic || rawParsed.main_topic || rawParsed.topic || rawParsed.title || firstBoardText;
      rawParsed.lectureTitle = rawParsed.lectureTitle || rawParsed.title || rawParsed.lecture_title || `Lecture: ${rawParsed.mainTopic}`;
      rawParsed.durationMinutes = typeof rawParsed.durationMinutes === 'number' ? rawParsed.durationMinutes : (parseInt(rawParsed.durationMinutes || rawParsed.duration_minutes || rawParsed.duration) || durationMinutes || 0);

      if (Array.isArray(rawParsed.possibleMissingConcepts)) {
        rawParsed.possibleMissingConcepts = rawParsed.possibleMissingConcepts.map((item: any) => {
          if (typeof item === 'string') {
            return { suggestion: item, reason: 'Identified concept from whiteboard context', evidence: [] };
          }
          return item;
        });
      }

      if (Array.isArray(rawParsed.possibleConfusions)) {
        rawParsed.possibleConfusions = rawParsed.possibleConfusions.map((item: any) => {
          if (typeof item === 'string') {
            return { suggestion: item, reason: 'Check visual relationships on board', evidence: [] };
          }
          return item;
        });
      }

      if (!rawParsed.grounding || typeof rawParsed.grounding !== 'object') {
        rawParsed.grounding = {
          observations: currentStrokes.map((s) => s.text).filter(Boolean).slice(0, 5),
          inferences: ['Generated by Gemini AI'],
          uncertainties: [],
        };
      }
    }

    rawParsed.providerMetadata = {
      provider: 'gemini',
      model: usedModelName,
      fallbackUsed: false,
    };

    const parsedRes = targetSchema.safeParse(rawParsed);
    if (parsedRes.success) {
      return parsedRes.data;
    }

    console.warn('[AIService Lecture] Schema validation mismatch, applying safe defaults:', parsedRes.error.format());
    return rawParsed;
  }
}

export const aiService = new AIService();
